// Simple PDF generator utility
export function generateSimplePDF(fileName: string): Blob {
  // Create PDF lines array (ensures proper newlines)
  const pdfLines = [
    '%PDF-1.4',
    '1 0 obj',
    '<< /Type /Catalog /Pages 2 0 R >>',
    'endobj',
    '2 0 obj',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    'endobj',
    '3 0 obj',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >> >> >>',
    'endobj',
    '4 0 obj',
    '<< /Length 280 >>',
    'stream',
    'BT',
    '/F1 24 Tf',
    '50 720 Td',
    `(${fileName.replace('.pdf', '')}) Tj`,
    '0 -30 Td',
    '/F1 14 Tf',
    '(Generated by SCORE) Tj',
    '0 -50 Td',
    '/F1 16 Tf',
    '(AI Music Transcription) Tj',
    '0 -40 Td',
    '/F1 12 Tf',
    '(Sheet Music Score) Tj',
    '0 -30 Td',
    '/F1 10 Tf',
    '(This is a demo PDF file.) Tj',
    'ET',
    'endstream',
    'endobj',
    'xref',
    '0 5',
    '0000000000 65535 f ',
    '0000000009 00000 n ',
    '0000000058 00000 n ',
    '0000000125 00000 n ',
    '0000000299 00000 n ',
    'trailer',
    '<< /Size 5 /Root 1 0 R >>',
    'startxref',
    '627',
    '%%EOF'
  ];
  
  // Join with actual newlines
  const pdfContent = pdfLines.join('\n');
  
  return new Blob([pdfContent], { type: 'application/pdf' });
}
